name: build-mac

on: 
  workflow_dispatch:

jobs:
  macos:
    runs-on: macos-latest
    steps:

      - name: Checkout project
        uses: actions/checkout@v2

      - name: Patch scripts
        run: |
          ruby -pi -e 'gsub("libturbojpeg", "libjpeg")' OSXvnc.xcodeproj/project.pbxproj
          ruby -pi -e 'gsub("/opt/libjpeg-turbo", "/usr/local")' OSXvnc.xcodeproj/project.pbxproj

      - name: Build libjpeg
        run: ./build-libjpeg-turbo.sh

      - name: Build OSXvnc
        run: xcodebuild

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "/tmp/VineServer.dmg"
          name: latest
          tag: latest
          commit: main
          prerelease: true
          allowUpdates: true
          omitBody: true
          omitBodyDuringUpdate: true 
          token: ${{ secrets.GITHUB_TOKEN }}
